# Generated by Django 5.2.3 on 2025-09-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subject_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='batch_id',
        ),
    ]
