# Generated by Django 5.2.3 on 2025-08-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultyleave',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='FacultyLeave',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='FacultySubject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
