# Generated by Django 5.2.3 on 2025-09-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_timeslot_alter_timetable_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.batch'),
        ),
    ]
